### ISSUE TITLE
页面不会hot reload

### ISSUE THREAD

**Issue by wait-hua** [nianiaJR/assets-with-webpack#2]
请问下 这个代码更新了，但是页面不会hot reload, 需要手动刷新页面，请问这个要怎么配置？

**Comment by nianiaJR** [comment]
https://github.com/nianiaJR/assets-with-webpack/commit/dee331754dad3eeab0b979c133c061d65ff6f157 已经修复了，你可以拉下最新代码，不好意思才看见
